service: my-serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000